name: Deploy Flutter Web to GitHub Pages (per branch)

on:
  push:
    branches: [ '**' ]  # Build on all branches

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: |
          flutter build web --base-href="/dry_living_mock_wall_unit/${GITHUB_REF##*/}/"
          mkdir -p out/${GITHUB_REF##*/}
          cp -r build/web/* out/${GITHUB_REF##*/}/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          publish_branch: gh-pages
